// <auto-generated />
using Domain.IPL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.IPL.Migrations.Lifeform
{
    [DbContext(typeof(LifeformContext))]
    partial class LifeformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("EukaryoteSequence");

            modelBuilder.Entity("Domain.DL.Models.LifeformModels.Eukaryote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [EukaryoteSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.DL.Models.LifeformModels.Animalia", b =>
                {
                    b.HasBaseType("Domain.DL.Models.LifeformModels.Eukaryote");

                    b.Property<bool>("IsBird")
                        .HasColumnType("bit");

                    b.Property<byte>("MaximumOffspringsPerMating")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MinimumOffspringsPerMating")
                        .HasColumnType("tinyint");

                    b.ToTable("Animalia");
                });

            modelBuilder.Entity("Domain.DL.Models.LifeformModels.Plantae", b =>
                {
                    b.HasBaseType("Domain.DL.Models.LifeformModels.Eukaryote");

                    b.Property<double>("MaximumHeight")
                        .HasColumnType("float");

                    b.ToTable("Plantae");
                });
#pragma warning restore 612, 618
        }
    }
}
